
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:14
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: petrovkrs/ros_bank_backend
    env_file: .env
    volumes:
      - static:/app/static/
    depends_on:
      - db
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432

  frontend:
    image: petrovkrs/ros_bank_frontend
    env_file: .env
    command: cp -r /app/dist/. /frontend_static/
    volumes:
      - static:/var/html/frontend_static
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - drf-yasg:/var/html/static/
      - static:/var/html/static/
#      - ./frontend/dist:/usr/share/nginx/html/
    depends_on:
      - backend
      - frontend
