version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/app/static
      - media:/media
    depends_on:
      - db

#  frontend:
#    build: ./frontend/
#    env_file: .env
#    command: cp -r /app/build/. /frontend_static/
#    volumes:
#      - static:/frontend_static
#    depends_on:
#      - backend

  nginx:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:app/static/
      - media:/media/
    depends_on:
      - backend