# Generated by Django 4.2 on 2024-10-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="managerteam",
            managers=[],
        ),
        migrations.RemoveConstraint(
            model_name="managerteam",
            name="unique_username_email",
        ),
        migrations.RemoveField(
            model_name="managerteam",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="managerteam",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="managerteam",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="managerteam",
            name="username",
        ),
        migrations.AlterField(
            model_name="managerteam",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="managerteam",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="managerteam",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="managerteam",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="managerteam",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="managerteam",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Фамилия"),
        ),
    ]
