# Generated by Django 4.2 on 2024-10-05 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetrainingapplication',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetrainingapplication',
            name='training_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainingapplication', verbose_name='Заявка на обучение'),
        ),
        migrations.AddField(
            model_name='employeeteam',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill', verbose_name='Навык'),
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='employeekeyskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeekeyskill',
            name='key_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.keyskill', verbose_name='Ключевой навык'),
        ),
        migrations.AddField(
            model_name='employeekeypeople',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keys_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeekeypeople',
            name='key_people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.keypeople', verbose_name='Key people'),
        ),
        migrations.AddField(
            model_name='employeegrade',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeegrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade', verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='employeeexpectedskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeexpectedskill',
            name='expected_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expectedskill', verbose_name='Ожидаемый навык'),
        ),
        migrations.AddField(
            model_name='employeeengagement',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeengagement',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.engagement', verbose_name='Вовлеченность'),
        ),
        migrations.AddField(
            model_name='employeedevelopmentplan',
            name='development_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.developmentplan', verbose_name='План развития'),
        ),
        migrations.AddField(
            model_name='employeedevelopmentplan',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='development_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeecompetency',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competency', verbose_name='Компетенция'),
        ),
        migrations.AddField(
            model_name='employeecompetency',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_competencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeebusfactor',
            name='bus_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.busfactor', verbose_name='Bus фактор'),
        ),
        migrations.AddField(
            model_name='employeebusfactor',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bus_factors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencyforexpectedskill',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competency'),
        ),
        migrations.AddField(
            model_name='competencyforexpectedskill',
            name='expected_skill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.expectedskill'),
        ),
        migrations.AddConstraint(
            model_name='skillforcompetency',
            constraint=models.UniqueConstraint(fields=('skill', 'competency'), name='unique_skill_competency'),
        ),
        migrations.AddConstraint(
            model_name='positioncompetency',
            constraint=models.UniqueConstraint(fields=('position', 'competency'), name='unique_position_competency'),
        ),
        migrations.AddConstraint(
            model_name='competencyforexpectedskill',
            constraint=models.UniqueConstraint(fields=('expected_skill', 'competency'), name='unique_expected_skill_competency'),
        ),
    ]
