# Generated by Django 4.2 on 2024-10-07 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssesmentSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assesmentskill_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название оценки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка навыка",
                "verbose_name_plural": "Оценки навыков",
                "ordering": ("assesmentskill_name",),
            },
        ),
        migrations.CreateModel(
            name="EmployeeAssesmentSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assesment",
                    models.IntegerField(
                        default=0, verbose_name="Оценка навыка сотрудника"
                    ),
                ),
                (
                    "assesmentskill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.assesmentskill",
                        verbose_name="Оценка навыка сотрудника",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assesments_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка навыка сотрудника",
                "verbose_name_plural": "Оценки навыков сотрудников",
                "ordering": ("employee",),
            },
        ),
    ]
