# Generated by Django 4.2 on 2024-10-04 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busfactor',
            options={'ordering': ('bus_factor_name',), 'verbose_name': 'Bus Фактор', 'verbose_name_plural': 'Bus Факторы'},
        ),
        migrations.AlterModelOptions(
            name='competency',
            options={'ordering': ('competency_name',), 'verbose_name': 'Компетенция', 'verbose_name_plural': 'Компетенции'},
        ),
        migrations.AlterModelOptions(
            name='competencyforexpectedskill',
            options={'verbose_name': 'Компетенция для ожидаемого навыка', 'verbose_name_plural': 'Компетенции для ожидаемых навыков'},
        ),
        migrations.AlterModelOptions(
            name='developmentplan',
            options={'ordering': ('plan_name',), 'verbose_name': 'План развития', 'verbose_name_plural': 'Планы развития'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('first_name',), 'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='employeebusfactor',
            options={'ordering': ('bus_factor',), 'verbose_name': 'Bus Фактор сотрудника', 'verbose_name_plural': 'Bus Факторы сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeecompetency',
            options={'ordering': ('competency',), 'verbose_name': 'Компетенция сотрудника', 'verbose_name_plural': 'Компетенции сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeedevelopmentplan',
            options={'ordering': ('development_plan',), 'verbose_name': 'План развития сотрудника', 'verbose_name_plural': 'Планы развития сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeeengagement',
            options={'ordering': ('engagement_level',), 'verbose_name': 'Вовлеченность сотрудника', 'verbose_name_plural': 'Вовлеченность сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeeexpectedskill',
            options={'ordering': ('expected_skill',), 'verbose_name': 'Ожидаемый навык сотрудника', 'verbose_name_plural': 'Ожидаемые навыки сотрудниов'},
        ),
        migrations.AlterModelOptions(
            name='employeegrade',
            options={'ordering': ('grade',), 'verbose_name': 'Класс сотрудника', 'verbose_name_plural': 'Классы сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeekeypeople',
            options={'ordering': ('key_people',), 'verbose_name': 'Key People сотрудника', 'verbose_name_plural': 'Key People сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeekeyskill',
            options={'ordering': ('key_skill',), 'verbose_name': 'Ключевой навык сотрудника', 'verbose_name_plural': 'Ключевые навыки сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeeposition',
            options={'ordering': ('position',), 'verbose_name': 'Должность сотрудника', 'verbose_name_plural': 'Должности сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeeskill',
            options={'ordering': ('skill',), 'verbose_name': 'Навык сотрудника', 'verbose_name_plural': 'Навыки сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeeteam',
            options={'ordering': ('team',), 'verbose_name': 'Команда сотрудника', 'verbose_name_plural': 'Команды сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='employeetrainingapplication',
            options={'ordering': ('training_application',), 'verbose_name': 'Заявка на обучение сотрудника', 'verbose_name_plural': 'Заявки на обучение сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='engagement',
            options={'ordering': ('engagement_name',), 'verbose_name': 'Вовлеченность', 'verbose_name_plural': 'Вовлеченности'},
        ),
        migrations.AlterModelOptions(
            name='expectedskill',
            options={'ordering': ('expected_skill_name',), 'verbose_name': 'Ожидаемый навык', 'verbose_name_plural': 'Ожидаемые навыки'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ('grade_name',), 'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='keypeople',
            options={'ordering': ('key_people_name',), 'verbose_name': 'Вовлеченность сотрудника', 'verbose_name_plural': 'Вовлеченность сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='keyskill',
            options={'ordering': ('skill_name',), 'verbose_name': 'Ключевой навык', 'verbose_name_plural': 'Ключевые навыки'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('position_name',), 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='positioncompetency',
            options={'verbose_name': 'Должность к компетенции', 'verbose_name_plural': 'Должности к компетенциям'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('skill_name',), 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='skillforcompetency',
            options={'verbose_name': 'Навык для компетенции', 'verbose_name_plural': 'Навыки для компетенций'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='teamposition',
            options={'ordering': ('team',), 'verbose_name': 'Должность для команды', 'verbose_name_plural': 'Должности для команд'},
        ),
        migrations.AlterModelOptions(
            name='trainingapplication',
            options={'ordering': ('training_name',), 'verbose_name': 'Заявка на обучение', 'verbose_name_plural': 'Заявки на обучение'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='bus_factor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='key_people',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeebusfactor',
            name='bus_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_bus_factors', to='core.busfactor', verbose_name='Bus фактор'),
        ),
        migrations.AlterField(
            model_name='employeecompetency',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_competencies', to='core.competency', verbose_name='Компетенция'),
        ),
        migrations.AlterField(
            model_name='employeedevelopmentplan',
            name='development_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_development_plans', to='core.developmentplan', verbose_name='План развития'),
        ),
        migrations.AlterField(
            model_name='employeeengagement',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_engagements', to='core.engagement', verbose_name='Вовлеченность'),
        ),
        migrations.AlterField(
            model_name='employeeexpectedskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='employeeexpectedskill',
            name='expected_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_expected_skills', to='core.expectedskill', verbose_name='Ожидаемый навык'),
        ),
        migrations.AlterField(
            model_name='employeegrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_grades', to='core.grade', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='employeekeypeople',
            name='key_people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_keys_peoples', to='core.keypeople', verbose_name='Key people'),
        ),
        migrations.AlterField(
            model_name='employeekeyskill',
            name='key_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_key_skills', to='core.keyskill', verbose_name='Ключевой навык'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_positions', to='core.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='core.skill', verbose_name='Навык'),
        ),
        migrations.AlterField(
            model_name='employeeteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_teams', to='core.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='employeetrainingapplication',
            name='training_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_training_applications', to='core.trainingapplication', verbose_name='Заявка на обучение'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_name',
            field=models.CharField(max_length=255, verbose_name='Название класса'),
        ),
        migrations.AddConstraint(
            model_name='competencyforexpectedskill',
            constraint=models.UniqueConstraint(fields=('expected_skill', 'competency'), name='unique_expected_skill_competency'),
        ),
        migrations.AddConstraint(
            model_name='positioncompetency',
            constraint=models.UniqueConstraint(fields=('position', 'competency'), name='unique_position_competency'),
        ),
        migrations.AddConstraint(
            model_name='skillforcompetency',
            constraint=models.UniqueConstraint(fields=('skill', 'competency'), name='unique_skill_competency'),
        ),
    ]
