# Generated by Django 4.2 on 2024-10-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_keypeople_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keypeople',
            options={'ordering': ('key_people_name',), 'verbose_name': 'Key people', 'verbose_name_plural': "Key people's"},
        ),
    ]
