# Generated by Django 4.2 on 2024-10-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_employeeteam_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeteam",
            name="employee",
        ),
        migrations.AddField(
            model_name="employeeteam",
            name="employee",
            field=models.ManyToManyField(
                related_name="teams", to="core.employee"
            ),
        ),
    ]
