# Generated by Django 4.2 on 2024-10-08 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_employeeteam_employee_employeeteam_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedevelopmentplan",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="development_plans",
                to="core.employee",
            ),
        ),
    ]
