# Generated by Django 4.2 on 2024-10-05 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeekeypeople',
            name='add_date',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата добавления ключевого сотрудника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeebusfactor',
            name='bus_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.busfactor', verbose_name='Bus фактор'),
        ),
        migrations.AlterField(
            model_name='employeebusfactor',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bus_factors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeecompetency',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competency', verbose_name='Компетенция'),
        ),
        migrations.AlterField(
            model_name='employeecompetency',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_competencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeedevelopmentplan',
            name='development_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.developmentplan', verbose_name='План развития'),
        ),
        migrations.AlterField(
            model_name='employeedevelopmentplan',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='development_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeengagement',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeengagement',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.engagement', verbose_name='Вовлеченность'),
        ),
        migrations.AlterField(
            model_name='employeeexpectedskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeexpectedskill',
            name='expected_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expectedskill', verbose_name='Ожидаемый навык'),
        ),
        migrations.AlterField(
            model_name='employeegrade',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeegrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='employeekeypeople',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keys_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeekeypeople',
            name='key_people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.keypeople', verbose_name='Key people'),
        ),
        migrations.AlterField(
            model_name='employeekeyskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeekeyskill',
            name='key_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.keyskill', verbose_name='Ключевой навык'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill', verbose_name='Навык'),
        ),
        migrations.AlterField(
            model_name='employeeteam',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='employeetrainingapplication',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeetrainingapplication',
            name='training_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainingapplication', verbose_name='Заявка на обучение'),
        ),
        migrations.AlterField(
            model_name='positioncompetency',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='core.position'),
        ),
    ]
