# Generated by Django 4.2 on 2024-10-12 21:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_keypeople_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], default=core.models.GradeTypeEnum['JUNIOR'], max_length=100, verbose_name='Тип класса'),
        ),
    ]
