# Generated by Django 4.2 on 2024-10-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_employeedevelopmentplan_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedevelopmentplan",
            name="add_date",
            field=models.DateField(
                db_index=True, verbose_name="Дата добавления сотрудника в план развития"
            ),
        ),
    ]
