# Generated by Django 4.2 on 2024-10-05 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employeekeypeople_add_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebusfactor',
            name='add_date',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата добавления bud-фактора сотрудника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeetrainingapplication',
            name='add_date',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата добавления заявки на обучение'),
            preserve_default=False,
        ),
    ]
