# Generated by Django 4.2 on 2024-10-05 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employeebusfactor_add_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedevelopmentplan',
            name='add_date',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата добавления сотрудника в план развития'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeengagement',
            name='add_date',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата вовлечения сотрудника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeekeyskill',
            name='add_date',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата добавления ключевого навыка сотрудника'),
            preserve_default=False,
        ),
    ]
