# Generated by Django 4.2 on 2024-10-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_employeedevelopmentplan_add_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeengagement",
            options={
                "ordering": ("performance_score",),
                "verbose_name": "Вовлеченность сотрудника",
                "verbose_name_plural": "Вовлеченность сотрудников",
            },
        ),
        migrations.RenameField(
            model_name="employeeengagement",
            old_name="engagement_level",
            new_name="performance_score",
        ),
        migrations.RemoveField(
            model_name="employeedevelopmentplan",
            name="development_progress",
        ),
        migrations.AddField(
            model_name="employeedevelopmentplan",
            name="performance_score",
            field=models.IntegerField(default=0, verbose_name="Процент развития"),
        ),
    ]
