# Generated by Django 4.2 on 2024-10-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_employeeengagement_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.SlugField(
                default=1,
                max_length=255,
                unique=True,
                verbose_name="Слаг команды",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employeedevelopmentplan",
            name="performance_score",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Процент развития"
            ),
        ),
    ]
