# Generated by Django 4.2 on 2024-10-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_team_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeskill",
            name="skill_level",
            field=models.IntegerField(
                default=0, verbose_name="Уровень навыка сотрудника"
            ),
        ),
    ]
