# Generated by Django 4.2 on 2024-10-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_employeeskill_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft')], default=2, max_length=4, verbose_name='Тип навыка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='employee_count',
            field=models.IntegerField(default=0, verbose_name='Количество сотрудников с данным навыком'),
        ),
    ]
