# Generated by Django 4.2 on 2024-10-14 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_employeedevelopmentplan_performance_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiongrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_positions', to='core.grade', verbose_name='Грейд'),
        ),
    ]
