# Generated by Django 4.2 on 2024-10-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_employeecompetency_actual_result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeposition",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="core.employee",
            ),
        ),
    ]
